version: '3.8'

networks:
  reactapp:

services:
  nginx-service:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
      - "443:443"
    volumes:
      - ./:/var/www/reactapp
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php74-service
      - mysql8-service
    networks:
      - reactapp

  php74-service:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
      args:
        TIMEZONE: Europe/Vilnius
    container_name: php74-container
    working_dir: /var/www/reactapp
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/reactapp
    networks:
      - reactapp

  mysql8-service:
    image: mysql:8.0.27
    container_name: mysql8-container
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./docker/.mysql:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - reactapp